import { describe, expect, it } from 'vitest';
import { ambientPad, engineCycle, musicPulse, noiseBurst, noiseLoop, sweep, tone } from '../../src/audio/synth';

/**
 * Synthesised audio.
 *
 * Every sound in the game is generated by this file, so these tests are the
 * only thing standing between a tuning change and a buffer full of clipping,
 * silence or NaN. They check the properties that would actually be audible as
 * a defect: finite samples, no clipping, an envelope that decays, and a pad
 * that loops without a click.
 */

const RATE = 48_000;

function fill(length: number, generator: (channel: Float32Array) => void): Float32Array {
  const channel = new Float32Array(length);
  generator(channel);
  return channel;
}

function peak(channel: Float32Array): number {
  let max = 0;
  for (const sample of channel) max = Math.max(max, Math.abs(sample));
  return max;
}

function rms(channel: Float32Array, from: number, to: number): number {
  let total = 0;
  for (let i = from; i < to; i++) total += (channel[i] as number) ** 2;
  return Math.sqrt(total / Math.max(1, to - from));
}

/** Mean absolute difference between neighbouring samples. */
function averageStep(channel: Float32Array): number {
  let total = 0;
  for (let i = 1; i < channel.length; i++) total += Math.abs((channel[i] as number) - (channel[i - 1] as number));
  return total / Math.max(1, channel.length - 1);
}

function assertClean(channel: Float32Array, name: string): void {
  for (let i = 0; i < channel.length; i++) {
    const sample = channel[i] as number;
    expect(Number.isFinite(sample), `${name} produced a non-finite sample at ${i}`).toBe(true);
    expect(Math.abs(sample), `${name} clipped at ${i}`).toBeLessThanOrEqual(1.0001);
  }
}

describe('tone', () => {
  it('produces a clean, decaying buffer', () => {
    const length = Math.floor(0.4 * RATE);
    const channel = fill(length, tone(length, RATE, { frequency: 440, decay: 8 }));
    assertClean(channel, 'tone');
    expect(peak(channel)).toBeGreaterThan(0.1);
    // Envelope: the tail is much quieter than the head.
    expect(rms(channel, length - 1000, length)).toBeLessThan(rms(channel, 100, 1100) * 0.5);
  });

  it('starts from silence, so there is no click on playback', () => {
    const length = Math.floor(0.2 * RATE);
    const channel = fill(length, tone(length, RATE, { frequency: 660, decay: 10 }));
    expect(Math.abs(channel[0] as number)).toBeLessThan(0.02);
  });

  it('follows the requested frequency', () => {
    // Count zero crossings over the first, loudest, tenth of a second.
    const frequency = 500;
    const window = Math.floor(0.1 * RATE);
    const channel = fill(window, tone(window, RATE, { frequency, decay: 0.5, harmonics: [1] }));
    let crossings = 0;
    for (let i = 1; i < window; i++) {
      if (Math.sign(channel[i] as number) !== Math.sign(channel[i - 1] as number)) crossings += 1;
    }
    expect(crossings / 2 / 0.1).toBeGreaterThan(frequency * 0.9);
    expect(crossings / 2 / 0.1).toBeLessThan(frequency * 1.1);
  });
});

describe('noiseBurst', () => {
  it('produces a clean, decaying burst', () => {
    const length = Math.floor(0.4 * RATE);
    const channel = fill(length, noiseBurst(length, RATE, { seed: 7, decay: 12, lowpass: 500 }));
    assertClean(channel, 'noiseBurst');
    expect(rms(channel, 0, 2000)).toBeGreaterThan(rms(channel, length - 2000, length) * 4);
  });

  it('is deterministic for a seed, and different across seeds', () => {
    const length = 4096;
    const a = fill(length, noiseBurst(length, RATE, { seed: 1, decay: 5, lowpass: 800 }));
    const b = fill(length, noiseBurst(length, RATE, { seed: 1, decay: 5, lowpass: 800 }));
    const c = fill(length, noiseBurst(length, RATE, { seed: 2, decay: 5, lowpass: 800 }));
    expect(Array.from(a)).toEqual(Array.from(b));
    expect(Array.from(a)).not.toEqual(Array.from(c));
  });

  it('stays stable at a high resonance rather than blowing up', () => {
    const length = Math.floor(0.5 * RATE);
    const channel = fill(length, noiseBurst(length, RATE, { seed: 3, decay: 4, lowpass: 3000, resonance: 0.9 }));
    assertClean(channel, 'resonant noiseBurst');
  });
});

describe('engineCycle', () => {
  it('produces one clean, loopable cycle', () => {
    const length = Math.floor(RATE / 110);
    const channel = fill(length, engineCycle(length, 7));
    assertClean(channel, 'engineCycle');
    expect(peak(channel)).toBeGreaterThan(0.2);
    // The loop point must not step, or the engine buzzes at the loop rate.
    const step = Math.abs((channel[0] as number) - (channel[length - 1] as number));
    expect(step).toBeLessThan(0.5);
  });

  it('has energy rather than being a bare sine', () => {
    const length = Math.floor(RATE / 110);
    const channel = fill(length, engineCycle(length, 7));
    // A pure sine has a crest factor of about 1.41; a combustion-like waveform
    // is peakier than that.
    expect(peak(channel) / rms(channel, 0, length)).toBeGreaterThan(1.3);
  });
});

describe('ambientPad', () => {
  it('produces clean stereo that loops seamlessly', () => {
    const seconds = 2;
    const length = Math.floor(seconds * RATE);
    const generator = ambientPad(seconds, RATE, { root: 55, seed: 5 });
    for (let channelIndex = 0; channelIndex < 2; channelIndex++) {
      const channel = new Float32Array(length);
      generator(channel, channelIndex);
      assertClean(channel, `ambientPad channel ${channelIndex}`);
      expect(peak(channel)).toBeGreaterThan(0.2);
      // Every partial completes a whole number of cycles, so the ends meet.
      expect(Math.abs((channel[0] as number) - (channel[length - 1] as number))).toBeLessThan(0.08);
    }
  });

  it('is normalised, so a tuning change cannot make it clip', () => {
    const seconds = 1;
    const length = Math.floor(seconds * RATE);
    const channel = new Float32Array(length);
    ambientPad(seconds, RATE, { root: 82, seed: 11 })(channel, 0);
    expect(peak(channel)).toBeCloseTo(0.55, 2);
  });

  it('differs between the two channels, so the bed has width', () => {
    const seconds = 1;
    const length = Math.floor(seconds * RATE);
    const left = new Float32Array(length);
    const right = new Float32Array(length);
    const generator = ambientPad(seconds, RATE, { root: 62, seed: 3 });
    generator(left, 0);
    generator(right, 1);
    expect(Array.from(left)).not.toEqual(Array.from(right));
  });
});

describe('noiseLoop', () => {
  it('loops without a click at the seam', () => {
    const channel = fill(2 * RATE, noiseLoop(2 * RATE, RATE, { seed: 5, lowpass: 4000 }));
    // The seam is what makes or breaks a bed that runs for a whole race: a
    // discontinuity here is a click every two seconds, and at these levels it
    // is the most audible thing in the mix.
    const step = Math.abs((channel[0] as number) - (channel[channel.length - 1] as number));
    const typical = averageStep(channel);
    expect(step).toBeLessThan(typical * 8);
    assertClean(channel, 'noiseLoop');
  });

  it('is band limited when a highpass is asked for', () => {
    const wide = fill(RATE, noiseLoop(RATE, RATE, { seed: 9, lowpass: 9000 }));
    const narrow = fill(RATE, noiseLoop(RATE, RATE, { seed: 9, lowpass: 9000, highpass: 400 }));
    // Removing the low end must remove energy, not merely move it.
    expect(rms(narrow, 0, narrow.length)).toBeLessThanOrEqual(rms(wide, 0, wide.length) * 1.05);
    assertClean(narrow, 'noiseLoop highpassed');
  });
});

describe('musicPulse', () => {
  it('produces clean stereo with width', () => {
    const left = fill(2 * RATE, (channel) => musicPulse(2, RATE, { root: 110, bpm: 96, seed: 3 })(channel, 0));
    const right = fill(2 * RATE, (channel) => musicPulse(2, RATE, { root: 110, bpm: 96, seed: 3 })(channel, 1));
    assertClean(left, 'musicPulse left');
    assertClean(right, 'musicPulse right');
    let different = 0;
    for (let i = 0; i < left.length; i++) {
      if (Math.abs((left[i] as number) - (right[i] as number)) > 1e-6) different += 1;
    }
    expect(different).toBeGreaterThan(left.length * 0.2);
  });

  it('is silent at the very start, so it fades in rather than clicking', () => {
    const channel = fill(RATE, (c) => musicPulse(1, RATE, { root: 110, bpm: 96, seed: 3 })(c, 0));
    expect(Math.abs(channel[0] as number)).toBeLessThan(0.02);
  });
});

describe('sweep', () => {
  it('rises in pitch and decays in level', () => {
    const length = Math.floor(0.6 * RATE);
    const channel = fill(length, sweep(length, RATE, { from: 200, to: 1200, decay: 3 }));
    assertClean(channel, 'sweep');

    const countCrossings = (from: number, to: number): number => {
      let crossings = 0;
      for (let i = from + 1; i < to; i++) {
        if (Math.sign(channel[i] as number) !== Math.sign(channel[i - 1] as number)) crossings += 1;
      }
      return crossings;
    };
    const window = Math.floor(0.05 * RATE);
    expect(countCrossings(length - window, length)).toBeGreaterThan(countCrossings(0, window));
    expect(rms(channel, length - 1000, length)).toBeLessThan(rms(channel, 0, 1000));
  });

  it('stays clean with the noise component mixed in', () => {
    const length = Math.floor(0.4 * RATE);
    const channel = fill(length, sweep(length, RATE, { from: 900, to: 220, decay: 10, noise: 0.6, seed: 31 }));
    assertClean(channel, 'noisy sweep');
  });
});
